#version 450
#include "../utils.comp"

layout(binding = 0) writeonly buffer dst_buffer {
    uint16_t colors[];
};

layout(binding = 1, rgba8ui) uniform readonly lowp uimage2D src_image;

void main() {
    u8vec4 rgba8 = u8vec4(imageLoad(src_image, GetImageCoord()));
    rgba8.rgb &= uint8_t(0xF8);
    uint16_t output_data = (rgba8.r << 8) | (rgba8.g << 3) | (rgba8.b >> 2) | (rgba8.a >> 7);
    colors[GetAddress()] = output_data;
}
