#version 450
#include "../utils.comp"

layout(binding = 0) writeonly buffer src_buffer {
    uint8_t raw[];
};

layout(binding = 1) readonly buffer dst_buffer {
    uint8_t stencil[];
};

void main() {
     ivec2 coord = GetImageCoord();
     uint32_t dst_addr = coord.y * gl_WorkGroupSize.x * gl_NumWorkGroups.x + coord.x;
     uint8_t val = stencil[dst_addr];
     raw[GetAddress() * 4 + 3] = val;
}
