#version 450
#include "../utils.comp"

layout(binding = 0) readonly buffer src_buffer {
    uint8_t raw[];
};

layout(binding = 1) writeonly buffer dst_buffer {
    uint8_t stencil[];
};

void main() {
     uint8_t val = raw[GetAddress() * 4 + 3];
     ivec2 coord = GetImageCoord();
     uint32_t dst_addr = coord.y * gl_WorkGroupSize.x * gl_NumWorkGroups.x + coord.x;
     stencil[dst_addr] = val;
}
