#version 450
#include "../utils.comp"

layout(binding = 0) readonly buffer src_buffer {
    uint16_t colors[];
};

layout(binding = 1, rgba8ui) uniform writeonly lowp uimage2D dst_image;

void main() {
    uint16_t input_data = colors[GetAddress()];
    u8vec3 color = u8vec3(u16vec3(input_data) >> u8vec3(11, 6, 1));
    color <<= 3;
    color |= color >> 5;
    uint16_t alpha = (input_data & 0x01us) * 0xFFus;
    imageStore(dst_image, GetImageCoord(), uvec4(color, alpha));
}